spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AdvertisingPlatform
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

